// <auto-generated />
namespace ResortManagement.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addPicTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPicTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006050614162_addPicTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
